### ISSUE TITLE
django version

### ISSUE THREAD

**Issue by nimasmi** [torchbox/cookiecutter-wagtail#13]
in https://github.com/torchbox/wagtail-cookiecutter/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/puppet/%7B%7Bcookiecutter.repo_name%7D%7D-production.pp#L18 (and the staging file too)

```
django_version   => '1.7',
```

but in https://github.com/torchbox/wagtail-cookiecutter/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/requirements.txt#L1

```
Django==1.8.3
```

**Comment by kaedroho** [comment]
Puppet config is removed from this repo
