### ISSUE TITLE
Make use of REDIS_URL environment variable in settings

### ISSUE THREAD

**Issue by alexgleason** [torchbox/cookiecutter-wagtail#20]
[dokku/dokku-redis](https://github.com/dokku/dokku-redis) automatically creates an environment variable called `REDIS_URL` when it gets linked to a container. It's a DSN in a format like this `redis://dokku-redis-hello:6379/0`

It might be helpful to use this variable in [settings/production.py](https://github.com/torchbox/cookiecutter-wagtail/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/settings/production.py#L94) so that further configuration isn't needed.

**Comment by alexgleason** [comment]
This works for me.

```python
# Redis
# Redis location can either be passed through with REDIS_HOST or REDIS_SOCKET

if 'REDIS_URL' in env:
    REDIS_URL = env['REDIS_URL']

else:
    REDIS_URL = None


if REDIS_URL is not None:
    CACHES = {
        'default': {
            'BACKEND': 'redis_cache.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'KEY_PREFIX': APP_NAME,
            'OPTIONS': {
                'CLIENT_CLASS': 'redis_cache.client.DefaultClient',
            }
        }
    }
```

Also, why does this file sometimes check `env`, but other times it checks `os.environ`?

For instance:

```python
if 'SECRET_KEY' in env:
    SECRET_KEY = env['SECRET_KEY']
```

compared to:

```python
if 'DATABASE_URL' in os.environ:
    DATABASES = {'default': dj_database_url.config()}
```

At the top of the file, `env` is defined as: `env = os.environ.copy()`

Why is it being copied?

**Comment by tomdyson** [comment]
> Why is it being copied?

To prevent accidental modification of `os.environ`. See http://stackoverflow.com/a/4453495
